### ISSUE TITLE
How to define Associations?

### ISSUE THREAD

**Issue by JonatanSalas** [felixfbecker/sequelize-decorators#28]
Hi!

I would like to know how to implement **associations** using your lib. 
Would you mind to add an example in the README.md or an example app? 

Thanks in advance!

**Comment by felixfbecker** [comment]
As associations are symmetric, they are by definition a cyclic reference between models. As such, they can't be defined statically - you need to define both models first, then you can associate them. This would not be possible with decorators in a non-hacky way. Basically the way you do it does not differ from how how you'd do it without decorators. One way to do it is shown in the TypeScript typings readme https://github.com/types/sequelize

**Comment by JonatanSalas** [comment]
@felixfbecker Thank you for your explanation!
