### ISSUE TITLE
Multiple errors in example when used with @types/sequelize

### ISSUE THREAD

**Issue by Ionaru** [felixfbecker/sequelize-decorators#46]
I've put the errors as comments under the lines that caused them.

```typescript
import {Sequelize, Model, DataTypes} from 'sequelize'
import {Options, Attribute} from 'sequelize-decorators'

const sequelize = new Sequelize(process.env.DB)
// TS2693: 'Sequelize' only refers to a type, but is being used as a value here.

@Options({
    sequelize,
    tableName: 'users'
})
export class User extends Model {
// TS2507: Type 'Model<any, any>' is not a constructor function type

    @Attribute({
        type: DataTypes.STRING,
// TS2693: 'DataTypes' only refers to a type, but is being used as a value here
        primaryKey: true
    })
    public username: string;

    @Attribute(DataTypes.STRING)
// TS2693: 'DataTypes' only refers to a type, but is being used as a value here
    public firstName: string;

    @Attribute()
    public lastName: string;

    get fullName(): string {
        return this.firstName + ' ' + this.lastName;
    }

    set fullName(fullName: string) {
        const names = fullName.split(' ');
        this.lastName = names.pop();
        this.firstName = names.join(' ');
    }
}
```

If I don't use the Sequelize typings, then the module is not defined and I'll have to make typings for all functions from scratch. Is there any way to use this package and still have Sequelize typings as well?

**Environment information**
OS: Linux Kubuntu 17.10
IDE: Intellij IDEA 2017.3 EAP
Node: 8.9.1
Typescript: 2.6.1
Sequelize: 4.22.6
Sequelize-decorators: 1.0.2
Types/sequelize: 4.0.79

**Comment by felixfbecker** [comment]
The example in the readme is only compatible with https://github.com/types/sequelize

**Comment by Ionaru** [comment]
So to use this with Typescript I'm expected to write my own definition file, is this correct?

**Comment by felixfbecker** [comment]
No, you are expected to install https://github.com/types/sequelize

**Comment by Ionaru** [comment]
Sorry, did not notice the link went to a /types/ url. Thanks
