### ISSUE TITLE
Example on README doesn't work

### ISSUE THREAD

**Issue by Kxze** [felixfbecker/sequelize-decorators#53]
Typescript complains I don't have typings for Sequelize installed, and when I install them I get a bunch of errors, such as:

`Type 'Model<any, any>' is not a constructor function type.`

and

`'DataTypes' only refers to a type, but is being used as a value here.`

**Comment by felixfbecker** [comment]
You need to install these typings: https://github.com/types/sequelize

**Comment by divineforest** [comment]
@felixfbecker I would add this info to the README since it's really not obvious. Thank you for your work!

**Comment by felixfbecker** [comment]
Feel free to do a PR

**Comment by divineforest** [comment]
@felixfbecker done
